In [60]:
import pandas as pd 
import numpy as np

In [61]:
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
df_vendas = pd.read_csv("vendas_tech.csv", low_memory=False)
display(df_vendas_format.sample(15))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_venda,Região
21710,21711,2023-09-26,São Paulo,Smartphone Samsung,2200.0,1,Cliente_3636,2200.0,Presencial,Sudeste
49248,49249,2023-02-20,Curitiba,iPhone 14,5500.0,1,Cliente_26605,5500.0,Presencial,Sul
99061,99062,2024-06-26,Curitiba,Notebook HP,3200.0,1,Cliente_19185,3200.0,Presencial,Sul
78072,78073,2023-01-27,Recife,Smartphone Samsung,2200.0,5,Cliente_5017,11000.0,Presencial,Nordeste
64540,64541,2023-01-23,Salvador,Smartphone Samsung,2200.0,1,Cliente_21350,2200.0,Presencial,Nordeste
53861,53862,2024-07-30,Porto Alegre,Teclado Mecânico,250.0,1,Cliente_29043,250.0,Presencial,Sul
29317,29318,2024-08-16,Curitiba,Mouse Gamer,120.0,1,Cliente_11733,120.0,Presencial,Sul
32570,32571,2024-12-12,São Paulo,"Monitor 27""",1200.0,5,Cliente_3661,6000.0,Presencial,Sudeste
89904,89905,2023-10-17,Belo Horizonte,Cabo HDMI,40.0,2,Cliente_2692,80.0,Presencial,Sudeste
10139,10140,2023-08-14,Rio De Janeiro,Teclado Mecânico,250.0,2,Cliente_111,500.0,Presencial,Sudeste
62084,62085,2023-12-28,São Paulo,Notebook Dell,3500.0,1,Cliente_14759,3500.0,Presencial,Sudeste
56954,56955,2024-12-09,Curitiba,"Monitor 27""",1200.0,1,Cliente_26989,1200.0,Presencial,Sul
56778,56779,2023-06-24,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_10713,120.0,Presencial,Sudeste
39904,39905,2023-09-28,Recife,Notebook Dell,3500.0,1,Cliente_14814,3500.0,Presencial,Nordeste
46311,46312,2023-12-19,Curitiba,iPhone 14,5500.0,1,Cliente_14527,5500.0,Presencial,Sul

In [62]:
# Removendo colunas desnecessárias
df_vendas_format = df_vendas.drop(columns=['Data_Base'])

# Completando espaços vazios com o valor que não foi preenchido por erro operacional
df_vendas_format['Loja'] = df_vendas_format['Loja'].fillna('Online')

# Corrigindo o formato dos dados
df_vendas_format['Data'] = pd.to_datetime(df_vendas_format['Data'], format="%Y-%m-%d")

# Padronizando textos
df_vendas_format['Loja'] = df_vendas_format['Loja'].str.strip().str.title()

# Removendo duplicatas
df_vendas_format = df_vendas_format.drop_duplicates(subset=['ID_Pedido'])


display(df_vendas_format.sample(15))
display(df_vendas_format.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
55179,55180,2024-07-30,Belo Horizonte,iPhone 14,5500.0,3,Cliente_24326
10855,10856,2023-01-19,Rio De Janeiro,Mouse Gamer,120.0,1,Cliente_26855
75832,75833,2024-06-04,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_28480
52681,52682,2024-04-01,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_18983
25493,25494,2024-08-12,Curitiba,Cabo HDMI,40.0,1,Cliente_6927
7473,7474,2023-06-04,Curitiba,Notebook Dell,3500.0,1,Cliente_6737
8679,8680,2024-08-20,Recife,Notebook HP,3200.0,1,Cliente_6818
59159,59160,2024-01-19,Online,Notebook Dell,3500.0,1,Cliente_12117
20581,20582,2024-09-12,Belo Horizonte,Mouse Gamer,120.0,2,Cliente_9516
86802,86803,2024-07-30,Curitiba,Smartphone Samsung,2200.0,1,Cliente_13342
19655,19656,2023-10-14,Porto Alegre,Notebook Dell,3500.0,1,Cliente_6126
27909,27910,2024-03-20,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_22778
6666,6667,2024-06-30,Salvador,Notebook Dell,3500.0,1,Cliente_26812
33944,33945,2024-03-19,Curitiba,Cabo HDMI,40.0,1,Cliente_14214
99972,99973,2024-01-22,Porto Alegre,"Monitor 27""",1200.0,1,Cliente_2608

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None

In [63]:
# Criar coluna de faturamento

df_vendas_format["Faturamento"] = df_vendas_format['Qtd'] * df_vendas_format["Preco_Unitario"]

# Criar coluna de forma de vendas

df_vendas_format["Forma_venda"] = np.where(df_vendas_format["Loja"] == "Online", "Online", "Presencial")

# Criar coluna que informa a região de vendas


dic_regioes = {
    'São Paulo' : 'Sudeste',
    'Belo Horizonte' : 'Sudeste',
    'Online' : 'Online',
    'Rio De Janeiro' : 'Sudeste',
    'Salvador' : 'Nordeste',
    'Recife' : 'Nordeste',
    'Curitiba' : 'Sul',
    'Porto Alegre' : 'Sul'
}

df_vendas_format['Região'] = df_vendas_format['Loja'].map(dic_regioes)

In [64]:
display(df_vendas_format)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_venda,Região
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

In [65]:
# Analise

df_vendas_sp = df_vendas_format[df_vendas_format['Loja'] == 'São Paulo']
display(df_vendas_sp)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_venda,Região
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,40.0,Presencial,Sudeste
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,2400.0,Presencial,Sudeste
21,22,2023-11-02,São Paulo,"Monitor 27""",1200.0,1,Cliente_28539,1200.0,Presencial,Sudeste
44,45,2023-03-24,São Paulo,iPhone 14,5500.0,2,Cliente_29552,11000.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99953,99954,2024-01-02,São Paulo,Smartphone Samsung,2200.0,1,Cliente_2020,2200.0,Presencial,Sudeste
99977,99978,2023-08-19,São Paulo,Teclado Mecânico,250.0,3,Cliente_18664,750.0,Presencial,Sudeste
99987,99988,2024-08-17,São Paulo,Mouse Gamer,120.0,2,Cliente_7855,240.0,Presencial,Sudeste
99994,99995,2023-02-01,São Paulo,Teclado Mecânico,250.0,1,Cliente_22028,250.0,Presencial,Sudeste
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste

In [ ]:
# analise com group by

# faturamento por loja 

analise_lojas = df_vendas_format[['Loja', 'Faturamento']].groupby('Loja').sum().sort_values(by="Faturamento", ascending=False).reset_index()
analise_lojas['Faturamento'] = analise_lojas['Faturamento'].map("R$ {:,.2f}".format)
display(analise_lojas)

             Loja       Faturamento
0        Salvador  R$ 42,300,610.00
1  Rio De Janeiro  R$ 42,294,720.00
2          Recife  R$ 42,190,390.00
3       São Paulo  R$ 42,090,690.00
4  Belo Horizonte  R$ 41,714,890.00
5    Porto Alegre  R$ 41,678,460.00
6        Curitiba  R$ 41,121,720.00
7          Online   R$ 6,080,850.00

                               Qtd
Loja           Produto
Belo Horizonte Cabo HDMI      2636
               Monitor 27"    2625
               Mouse Gamer    2465
               Notebook Dell  2654
               Notebook HP    2775

In [72]:
# faturamento por produto para loja 
    # Os produtos que venderam mais por loja
analise_produtos_por_loja = df_vendas_format[['Loja', 'Produto', 'Qtd']].groupby(['Loja', 'Produto']).sum()
with pd.option_context('display.max_rows', None):
    display(analise_produtos_por_loja)

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
               Smartphone Samsung  2597
               Teclado Mecânico    2609
               iPhone 14           2478
Curitiba       Cabo HDMI           2698
               Monitor 27"         2626
               Mouse Gamer         2600
               Notebook Dell       2517
               Notebook HP         2529
               Smartphone Samsung  2444
               Teclado Mecânico    2742
               iPhone 14           2652
Online         Cabo HDMI            403
               Monitor 27"          332
               Mouse Gamer          379
               Notebook Dell        369
               Notebook HP          442
               Smartphone Samsung   311
               Teclado Mecânico     343
               iPhone 14            390
Porto Alegre   Cabo HDMI           2571
               Monitor 27"         2655
               Mouse Gamer         2611
               Notebook Dell       2770
               Notebook HP         2511
               Smartphone Samsung  2603
               Teclado Mecânico    2598
               iPhone 14           2540
Recife         Cabo HDMI           2534
               Monitor 27"         2647
               Mouse Gamer         2639
               Notebook Dell       2566
               Notebook HP         2651
               Smartphone Samsung  2660
               Teclado Mecânico    2775
               iPhone 14           2652
Rio De Janeiro Cabo HDMI           2747
               Monitor 27"         2798
               Mouse Gamer         2652
               Notebook Dell       2534
               Notebook HP         2614
               Smartphone Samsung  2626
               Teclado Mecânico    2548
               iPhone 14           2702
Salvador       Cabo HDMI           2566
               Monitor 27"         2545
               Mouse Gamer         2711
               Notebook Dell       2512
               Notebook HP         2785
               Smartphone Samsung  2627
               Teclado Mecânico    2579
               iPhone 14           2671
São Paulo      Cabo HDMI           2649
               Monitor 27"         2796
               Mouse Gamer         2714
               Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735