In [2]:
import pandas as pd 
import numpy as np

In [3]:
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
df_vendas = pd.read_csv("vendas_tech.csv", low_memory=False)
display(df_vendas.sample(15))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
20649,20650,2023-02-20,São Paulo,iPhone 14,5500.0,1,Cliente_10148,NaN
80617,80618,2023-05-17,Salvador,"Monitor 27""",1200.0,1,Cliente_6558,NaN
330,331,2024-03-14,RIO DE JANEIRO,Notebook Dell,3500.0,1,Cliente_2081,NaN
74563,74564,2024-03-25,São Paulo,Cabo HDMI,40.0,1,Cliente_20013,NaN
10130,10131,2023-09-22,Salvador,Teclado Mecânico,250.0,1,Cliente_13509,NaN
83750,83751,2024-09-17,Belo Horizonte,Notebook Dell,3500.0,1,Cliente_24660,NaN
82115,82116,2023-10-27,Curitiba,Smartphone Samsung,2200.0,1,Cliente_5728,NaN
25813,25814,2023-08-16,São Paulo,Notebook HP,3200.0,1,Cliente_21992,NaN
5493,5494,2024-05-26,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_9826,NaN
27968,27969,2023-11-05,Recife,Notebook HP,3200.0,2,Cliente_10139,NaN
21202,21203,2024-01-16,Rio de Janeiro,Notebook HP,3200.0,1,Cliente_11785,NaN
43420,43421,2023-09-05,Rio de Janeiro,iPhone 14,5500.0,1,Cliente_7530,NaN
25907,25908,2023-01-07,Porto Alegre,Notebook Dell,3500.0,1,Cliente_21308,NaN
33280,33281,2024-09-23,São Paulo,Notebook Dell,3500.0,1,Cliente_16475,NaN
61828,61829,2024-09-19,São Paulo,Mouse Gamer,120.0,1,Cliente_3303,NaN

In [13]:
# Removendo colunas desnecessárias
df_vendas_format = df_vendas.drop(columns=['Data_Base'])

# Completando espaços vazios com o valor que não foi preenchido por erro operacional
df_vendas_format['Loja'] = df_vendas_format['Loja'].fillna('Online')

# Corrigindo o formato dos dados
df_vendas_format['Data'] = pd.to_datetime(df_vendas_format['Data'], format="%Y-%m-%d")

# Padronizando textos
df_vendas_format['Loja'] = df_vendas_format['Loja'].str.strip().str.title()

# Removendo duplicatas
df_vendas_format = df_vendas_format.drop_duplicates(subset=['ID_Pedido'])


display(df_vendas_format.sample(15))
display(df_vendas_format.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
67969,67970,2023-01-06,Porto Alegre,Cabo HDMI,40.0,1,Cliente_21731
23275,23276,2024-03-03,Salvador,iPhone 14,5500.0,1,Cliente_21933
36189,36190,2023-10-03,Salvador,Notebook Dell,3500.0,1,Cliente_6797
84428,84429,2024-01-08,Salvador,iPhone 14,5500.0,1,Cliente_24384
89263,89264,2023-06-18,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25857
9732,9733,2023-07-20,Recife,Mouse Gamer,120.0,1,Cliente_13375
94096,94097,2024-06-07,Curitiba,Notebook Dell,3500.0,1,Cliente_13245
45147,45148,2023-05-21,Porto Alegre,"Monitor 27""",1200.0,10,Cliente_5362
39442,39443,2024-09-12,Rio De Janeiro,"Monitor 27""",1200.0,1,Cliente_14242
81687,81688,2023-10-20,Salvador,Mouse Gamer,120.0,1,Cliente_17854
42036,42037,2024-05-24,São Paulo,Cabo HDMI,40.0,1,Cliente_17708
29032,29033,2024-05-02,Porto Alegre,Notebook Dell,3500.0,1,Cliente_25616
49252,49253,2024-08-25,São Paulo,Notebook HP,3200.0,2,Cliente_25579
80375,80376,2023-03-01,Curitiba,"Monitor 27""",1200.0,1,Cliente_9847
92415,92416,2024-01-06,Salvador,Mouse Gamer,120.0,1,Cliente_2561

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None